[package]
name = "miette"
version = "0.3.1"
authors = ["Kat Marchán <kzm@zkat.tech>"]
description = "Fancy diagnostic reporting library and protocol for us mere mortals who aren't compiler hackers."
categories = ["rust-patterns"]
repository = "https://github.com/zkat/miette"
documentation = "https://docs.rs/miette"
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
indenter = "0.3.3"
thiserror = "1.0.26"

[dev-dependencies]
thiserror = "1.0.26"
